In [28]:
import gym #import OpenAI Gym
import numpy as np #Import numpy

In [29]:
#This will run an instance of the CartPole-v0 environment for 1000 timesteps, rendering the environment at each step
env = gym.make('CartPole-v0')
observation=env.reset()
# observation  #[position of cart,velocity of cart,angle of pole,velocity of pole at its tip]
for _ in range(1000):
    env.render()
    env.step(env.action_space.sample()) # take a random action
env.close()

In [30]:
#Making random movements
env = gym.make('CartPole-v0')
#play the game for ten times
for i_episode in range(10):
    observation = env.reset()
    print("observation at reset:",observation)
    #objective of this game is to keep the pore vertical as long as possible
    count=0
    done=False
    while not done:
        #it will take astronomical amount of time (avoid it for real reinforcement learning)
        env.render() #render the system to the screen (without this graphical view is not shown)
        count+=1
        print("observation:",observation)
        # here action is either moving left or right
        action = env.action_space.sample() #api will provide a random action here(0 or 1 here)
        observation, reward, done, info = env.step(action) # telling env to make one step or make one movement
        if done:  #come out of the game if done is true
            print("Episode finished after {} timesteps".format(count+1))
            break
env.close()

observation at reset: [0.00761364 0.00662178 0.00961594 0.04126213]
observation: [0.00761364 0.00662178 0.00961594 0.04126213]
observation: [ 0.00774607  0.20160453  0.01044118 -0.24837143]
observation: [ 0.01177816  0.39657583  0.00547375 -0.53774278]
observation: [ 0.01970968  0.20137735 -0.00528111 -0.24334017]
observation: [ 0.02373722  0.00633123 -0.01014791  0.04767229]
observation: [ 0.02386385 -0.18864375 -0.00919446  0.33713627]
observation: [ 0.02009097 -0.38363366 -0.00245174  0.62690563]
observation: [ 0.0124183  -0.57872131  0.01008637  0.91881541]
observation: [ 8.43874964e-04 -7.73978140e-01  2.84626821e-02  1.21465111e+00]
observation: [-0.01463569 -0.57923474  0.0527557   0.93102122]
observation: [-0.02622038 -0.77502746  0.07137613  1.23980468]
observation: [-0.04172093 -0.9709897   0.09617222  1.55396638]
observation: [-0.06114073 -0.77714307  0.12725155  1.29277115]
observation: [-0.07668359 -0.58384733  0.15310697  1.04248295]
observation: [-0.08836053 -0.78063429 

In [31]:
#In the examples above, we’ve been sampling random actions from the environment’s action space. But what actually are those actions? Every environment comes with an action_space and an observation_space. These attributes are of type Space, and they describe the format of valid actions and observations
env = gym.make('CartPole-v0')
print(env.action_space)
#> Discrete(2)
print(env.observation_space)

Discrete(2)
Box(-3.4028234663852886e+38, 3.4028234663852886e+38, (4,), float32)


In [32]:
print(env.observation_space.high)
#> array([ 2.4       ,         inf,  0.20943951,         inf])
print(env.observation_space.low)
#> array([-2.4       ,        -inf, -0.20943951,        -inf])

[4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38]


In [33]:
from gym import spaces
space = spaces.Discrete(8) # Set with 8 elements {0, 1, 2, ..., 7}
x = space.sample()
assert space.contains(x)
assert space.n == 8